language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: HD0ZT3IKtBNSOayvvZWxtRx2UZ7o4pjRoqO+XCCJvHeHfwh6QcMtY0ctKgdUhoA8HDJstpPjN8pOlVh+nDOdQ5ejXyR919rGYYm7BddCbFzTX5eX1aE+PtKIvq+0KXG5CMC21B96BQpUrwCnZLJVTzeN82H4ZI6SBPEHFxvWaX6G15mh0BGrZkIfOiJVrK40rjNf11DEZHJfm7QIqnbkuJhtuyV06FvgrAcc4ROBn8AXXF5wgHbq3HtGyX3bS7FZ56tJjSAsNezEsa4YSvYUOYp8Yxt3VAYlRGzZ+o9sQ0zn6A/uDZbZ0eo5woHnK3Qe1asHYQzkZrklZt3E9Ly9YuHiBK7lQUl7/xhTGDZ7SzT7lqtuP3ytpol2Kym4xOzFcvXIE/TBub2vH2X5N0/9NPe3xFJNNinjB0fbGSYnsgyKDILalfZ4y4qwVvYMJWitBacBMk3m2nY6vs4IJU530u7ppg/B/UKGurPUuwVyB8sTROPPf+uLCFw8cmfCZsW0uoZuxQ80n4Dk7/CphKoGwMLh4av6FJxDCLGMS4ADh7vQXu6pBKD9U/P1ERnN0WjBS0RdeftuKcEePMqEcD2DFaTkgSa07+6C0mq3BA/rljZbEJu8DjDHvyASY4DbxV92voSmzviJmAKUupQmXbTZhqagLPRlUKeJu8WAhnZyCF4=
  app: scoresearch
  on:
    repo: Blakesters/ScoreSearch
